package com.way2automation.testcases;

import java.util.Hashtable;

import org.openqa.selenium.Alert;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.testng.Assert;
import org.testng.SkipException;
import org.testng.annotations.Test;

import com.way2automation.base.TestBase;
import com.way2automation.utilities.TestUtil;

public class AddCusTest extends TestBase {
	
	@Test(dataProviderClass=TestUtil.class,dataProvider="dp")//created a getData method below implemented dataprovider
	public void addCusTest(Hashtable<String,String> data) throws InterruptedException //passing hashtable as argument to retrieve the values from excel
	{
		if(!data.get("Runmode").equalsIgnoreCase("Y"))//setting up run modes for the test data retrieving the value from excel
		{
			throw new SkipException("Skipping the test case as the RunMode for data set is NO");
		}
		log.info("addCustomer testfall anfängt");
		click("addCust_CSS");//click method added in TestBase
		type("FirstName_CSS",data.get("firstName"));//values for firstName,lastName, postCode is extracted from excel dataprovider
		type("LastName_CSS",data.get("lastName"));
		type("PostCode_CSS",data.get("postCode"));
		click("addCustButton_CSS");//submitting all the details entered
		Alert alert = wait.until(ExpectedConditions.alertIsPresent());//switching to alerts using explicit wait, over here implicit wait will not work as it searches only on the webpage , but explicit wait can for Expected conditions i.e. alert
		Assert.assertTrue(alert.getText().contains(data.get("alertText")));//adding an assertion to check the alert pop-up message
		alert.accept();
		Thread.sleep(1000);
		log.info("Neue konto hinzugefugt");
		//Reporter.log(postCode);//Reporter class is used for test methods to log messages that will be included in the HTML reports generated by Testng getting screenshot
				
	}
	
	
	

}
