package com.way2automation.testcases;

import java.util.Hashtable;

import org.openqa.selenium.Alert;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.testng.annotations.Test;

import com.way2automation.base.TestBase;
import com.way2automation.utilities.TestUtil;

public class OpenAccountTest extends TestBase {//opening an account
	
	@Test(dataProviderClass=TestUtil.class,dataProvider="dp")//created a getData method present in util class to get data 
	public void openAccountTest(Hashtable<String,String> data) throws InterruptedException //passing hashtable as argument to retrieve the values from excel
	{
		
		log.info("openCustomer testfall anfängt");
		click("openAccount_CSS");
		select("customer_CSS",data.get("customer") );//getting the data for the customer column
		select("currency_CSS", data.get("currency"));//getting the data for the currency column
		click("process_CSS");
		Thread.sleep(1000);
		Alert alert = wait.until(ExpectedConditions.alertIsPresent());//switching to alerts using explicit wait, over here implicit wait will not work as it searches only on the webpage , but explicit wait can for Expected conditions i.e. alert
		alert.accept();
		
		log.info("Neue konto hinzugefugt");
		//Reporter.log(postCode);//Reporter class is used for test methods to log messages that will be included in the HTML reports generated by Testng getting screenshot
				
	}
	
	
	
	

}
